#将静态内容部署到GUUUB页面的简单工作流
 姓名    : 将静态内容部署到页面

在…上  :
  #继续以默认分支为目标
  推动  :
    分枝 : [ "main" ]

  #允许您从操作选项卡手动运行此工作流
  工作流程 :

#设置了使部署得以实现JUTUB页面的JUTUB_托肯权限
 准许 :
  目录 : 阅读
  页 : 书写
  令人印象深刻的 : 书写

#只允许一个并发部署,在正在进行的运行和最新的队列之间跳过排队的运行。
#但是,不要取消正在进行的运行,因为我们希望允许这些生产部署完成。
 并发的 :
  团体 : "pages"
  正在取消的 : 假的

 乔布斯  :
  #单一部署任务因为我们刚刚部署
  部署 :
    环境 :
      姓名 : 吉瑟布页
      乌拉圭网址 : $ { { steps.deployment.outputs.page_url } }
    逃跑 : 最新的
    台阶 :
      - 姓名 : 结帐
        使用 : 行动/结账@V4
      - 姓名 : 安装页
        使用 : 行动/配置页@V5
      - 姓名 : 上传艺术品
        使用 :  行动/上传-页面-艺术品@v3
        with :
          #上载整个储存库
          通道 : '.'
      - 姓名 : 部署到基特布页
        身份证 : 部署
        使用 : 行动/部署页@v4
